/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search_1"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put: operations["update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["balance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/projections/balances/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rebuild the balance projection from the journal
         * @description Detects accounts whose projected balance drifted from the posted journal lines, repairs them, and reports how many were corrected.
         */
        post: operations["rebuildBalances"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/advisor/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze a snapshot supplied by the caller
         * @description Useful for what-if analysis: you provide the figures, the advisor comments them.
         */
        post: operations["analyze"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/advisor/analyze-ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze the current state of the ledger
         * @description The server composes the snapshot from the trial balance (posted entries only), then asks the advisor.
         */
        post: operations["analyzeLedger"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journal-entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post: operations["record"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journal-entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journal-entries/{id}/post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journal-entries/{id}/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reverse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/trial-balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trial balance
         * @description Debits, credits and normal-side balance per account. `balanced` must be true if the ledger is consistent.
         */
        get: operations["trialBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountBalanceLineRequest: {
            /** Format: uuid */
            accountId: string;
            accountName: string;
            /** @enum {string} */
            accountType: "ASSET" | "LIABILITY" | "EQUITY" | "REVENUE" | "EXPENSE";
            /** @description Exact decimal amount, as a string (a JSON number is also accepted) */
            balance: string;
        };
        AccountResponse: {
            active: boolean;
            currencyCode: string;
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            type: "ASSET" | "LIABILITY" | "EQUITY" | "REVENUE" | "EXPENSE";
        };
        AdviceResponse: {
            /** Format: date-time */
            generatedAt: string;
            provider: string;
            recommendations: components["schemas"]["RecommendationResponse"][];
        };
        AnalyzeSnapshotRequest: {
            balances: components["schemas"]["AccountBalanceLineRequest"][];
            currencyCode: string;
            /** @description Exact decimal amount, as a string (a JSON number is also accepted) */
            totalCredits: string;
            /** @description Exact decimal amount, as a string (a JSON number is also accepted) */
            totalDebits: string;
        };
        BalanceResponse: {
            /** @description Exact decimal amount, serialized as a string */
            amount: string;
            currencyCode: string;
        };
        CreateAccountRequest: {
            currencyCode: string;
            name: string;
            /** @enum {string} */
            type: "ASSET" | "LIABILITY" | "EQUITY" | "REVENUE" | "EXPENSE";
        };
        JournalEntryLineRequest: {
            /** Format: uuid */
            accountId: string;
            /** @description Exact decimal amount, as a string (a JSON number is also accepted) */
            amount: string;
            /** @enum {string} */
            entryType: "DEBIT" | "CREDIT";
        };
        JournalEntryLineResponse: {
            /** Format: uuid */
            accountId: string;
            /** @description Exact decimal amount, serialized as a string */
            amount: string;
            /** @enum {string} */
            entryType: "DEBIT" | "CREDIT";
        };
        JournalEntryResponse: {
            /** Format: date-time */
            createdAt: string;
            description: string;
            /** Format: uuid */
            id: string;
            lines: components["schemas"]["JournalEntryLineResponse"][];
            /**
             * Format: date-time
             * @description Null while the entry is a draft
             */
            postedAt: string | null;
            /**
             * Format: uuid
             * @description Set when this entry reverses another one
             */
            reversalOfId: string | null;
            /** @enum {string} */
            status: "DRAFT" | "POSTED" | "REVERSED";
        };
        MeResponse: {
            /** Format: uuid */
            tenantId: string;
            /** Format: uuid */
            userId: string;
        };
        PagedResponseAccountResponse: {
            content: components["schemas"]["AccountResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        PagedResponseJournalEntryResponse: {
            content: components["schemas"]["JournalEntryResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        RebuildProjectionResponse: {
            /** Format: int32 */
            accountsCorrected: number;
            /** Format: int32 */
            accountsRebuilt: number;
        };
        RecommendationResponse: {
            category: string;
            detail: string;
            severity: string;
            title: string;
        };
        RecordJournalEntryRequest: {
            currencyCode: string;
            description: string;
            lines: components["schemas"]["JournalEntryLineRequest"][];
        };
        TrialBalanceLineResponse: {
            /** Format: uuid */
            accountId: string;
            accountName: string;
            accountType: string;
            /** @description Exact decimal amount, serialized as a string */
            balance: string;
            /** @description Exact decimal amount, serialized as a string */
            totalCredits: string;
            /** @description Exact decimal amount, serialized as a string */
            totalDebits: string;
        };
        TrialBalanceResponse: {
            balanced: boolean;
            currencyCode: string;
            /** Format: date-time */
            generatedAt: string;
            lines: components["schemas"]["TrialBalanceLineResponse"][];
            /** @description Exact decimal amount, serialized as a string */
            totalCredits: string;
            /** @description Exact decimal amount, serialized as a string */
            totalDebits: string;
        };
        UpdateAccountRequest: {
            active: boolean;
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search_1: {
        parameters: {
            query?: {
                type?: "ASSET" | "LIABILITY" | "EQUITY" | "REVENUE" | "EXPENSE";
                active?: boolean;
                name?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedResponseAccountResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAccountRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    balance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BalanceResponse"];
                };
            };
        };
    };
    rebuildBalances: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RebuildProjectionResponse"];
                };
            };
        };
    };
    analyze: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeSnapshotRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdviceResponse"];
                };
            };
        };
    };
    analyzeLedger: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdviceResponse"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: {
                status?: "DRAFT" | "POSTED" | "REVERSED";
                createdFrom?: string;
                createdTo?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedResponseJournalEntryResponse"];
                };
            };
        };
    };
    record: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordJournalEntryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["JournalEntryResponse"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["JournalEntryResponse"];
                };
            };
        };
    };
    post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["JournalEntryResponse"];
                };
            };
        };
    };
    reverse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["JournalEntryResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    trialBalance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TrialBalanceResponse"];
                };
            };
        };
    };
}
